on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          wget https://gtfs.mot.gov.il/gtfsfiles/israel-public-transportation.zip
          unzip -p israel-public-transportation.zip routes.txt > routes.txt

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add routes.txt
          git commit -m "update routes" || true
          git push